[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
hex = "0.4.3"
num-bigint = "0.4.3"
num-traits = "0.2.15"
radix_fmt = "1.0.0"
